# Generated by Django 5.2 on 2025-05-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argioapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='alt',
            field=models.CharField(default='alt_to_change', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='thumbnail_url',
            field=models.URLField(blank=True, help_text='Thumbnail for catalogue view', null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='url',
            field=models.URLField(help_text='Main content URL: YouTube, image, 3D model, etc.'),
        ),
    ]
