# Generated by Django 5.2 on 2025-07-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('argioapp', '0002_content_alt_content_thumbnail_url_alter_content_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='grid_order',
            field=models.PositiveIntegerField(default=90, help_text='Define order within the content type selected.'),
            preserve_default=False,
        ),
    ]
